### ISSUE TITLE
datomic not throwing exception on wrong value type of anattibite?

### ISSUE THREAD

**Issue by piyushmandovra** [moquist/datomic-schematode#2]
when bymistake i put wrong valueType 
example..
(def schema1
  [{:namespace :users
    :attrs [[:email :string :indexed]
            [:pwd :string ] ]}
   {:namespace :customers
    :attrs [[:name :string]
            [:money :int]
            [:users :ref]]})

i.e. wrong :db/valueType of points in customers namespace.

and try to load schema using datomic-schematode/load-schema! method 
schema got created with only users namespace attribute and all customersnamespace attribute got discarded....
without throwing any exception.......!!!

**Comment by moquist** [comment]
Sorry for the delay! I saw this before the holidays, but couldn't get back to it until now.

If this is still an issue, can you please show some more of your code? I get exceptions when I `deref` the futures returned from `d/transact`, which are then returned from `load-schema!`.

See https://github.com/moquist/schematode-crazy-attrs for a quick demo.

I'm going to close this at this point, since everything seems to be working. If it's still an issue let me know.

Cheers!
